### ISSUE TITLE
Error when receive POST

### ISSUE THREAD

**Issue by pozitp** [mahenzon/aioalice#16]
![изображение](https://user-images.githubusercontent.com/61188367/163703782-ab84a376-9d41-432f-9d92-d4259b6629af.png)
![изображение](https://user-images.githubusercontent.com/61188367/163703874-b62a7917-41a1-466c-9c86-30a295d4f93e.png)
![Снимок экрана от 2022-04-17 13-45-25](https://user-images.githubusercontent.com/61188367/163704050-4babe039-d176-4b6e-93c3-f698dfe93204.png)

That is my mistake, or problem in library/ngrok? IDK, I use simple example with Hello World, but it doesn't work. Use ngrok, run it by command `ngrok http 3001`

OS: Fedora 36 Beta
Library: aioalice 1.5.0
ngrok: 3.0.2
Python: 3.10.4

**Comment by mahenzon** [comment]
Hey! Thank you for your report

This fix should help: #17

You'll need to update to 1.5.1
https://github.com/mahenzon/aioalice/releases/tag/1.5.1
