### ISSUE TITLE
Состояния

### ISSUE THREAD

**Issue by renat2006** [mahenzon/aioalice#20]
Как сделать хэндлер, который будет доступен из любого состояния? Допустим на команду прекрати, навык должен незамедлительно устанавливать свою работу, но это работает, только на конкретном состоянии, то есть на другом уже не работает. В примере про машину состояний также не работает

**Comment by mahenzon** [comment]
Привет! 
А в каком порядке у вас расположены обработчики? В хэндлере указывали `state="*" `?

**Comment by renat2006** [comment]
Нет не указывал, то есть так должно сработать?

**Comment by renat2006** [comment]
А есть какая-то документация, просто в примерах нет таких тонкостей?

**Comment by mahenzon** [comment]
Должно сработать, да. Нет, до документации руки так и не дошли 🙃

**Comment by renat2006** [comment]
Хорошо, спасибо
