### ISSUE TITLE
Игнорировать лишние параметры в JSON request от Алисы

### ISSUE THREAD

**Issue by LionZXY** [mahenzon/aioalice#9]
# Основная мысль

Предлагаю во всех объектах добавить игнорирование дополнительных параметров при парсинге JSON

# Мотивация
1) API в основном расширяется, а не меняется. Это значит что с большой вероятностью при обновлении API навык будет продолжать работать
2) Поддержка дебажных JSON с полями типо `__comment`
3) Постепенная миграция со старой версии библиотеки на новую (не будет крашиться)

В связи со спецификой разработки навыков (обычно это пет-проекты) при ближайшем расширении API протокола некоторая часть навыков просто умрет навсегда

# В результате
- Повышение стабильности работы навыков на библиотеке aioalice (1)
- Поддержка API основанных на API алисы (2,3)

**Comment by mahenzon** [comment]
Есть пара идей, что с этим сделать, в отдельной ветке поэксперементирую, уже есть наработки

**Comment by mahenzon** [comment]
Fixed in https://github.com/mahenzon/aioalice/releases/tag/1.3.0
